name = "rucai4m2025-finite-field-final"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Rucai4m2025FiniteFieldFinal"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Rucai4m2025FiniteFieldFinal"
