import Mathlib

/-!
# Finite Fields with Cyclic Multiplicative Groups

This file proves that every field with a cyclic multiplicative group is finite.

## Main Results

- `Field.finite_of_cyclic_units`: The main theorem showing that if F is a field
  with cyclic unit group Fˣ, then F is finite.

## Proof Strategy

1. `finite_of_finite_units`: Basic lemma that if Fˣ is finite, then F is finite
2. `orderOf_eq_zero_of_cyclic_of_infinite`: Non-identity element in an infinite cyclic group is of
                                            order 0
3. `simple_extension_of_cyclic_generator`: Adjoining a generator of cyclic unit group
                                           gives the whole field
4. `Field.finite_of_char_two_of_cyclic_units`: Proves the main theorem in the characteristic 2 case
-/

open Set

/-- If the group of units of a field F is finite, then F itself is finite.
    This follows from the fact that F = Fˣ ∪ {0}. -/
lemma finite_of_finite_units (F : Type*) [Field F] [Finite Fˣ] : Finite F := by
  -- Show that F = Fˣ ∪ {0}
  have h_eq : (Set.univ : Set F) = Set.range Units.val ∪ {0} := by
    ext x
    simp only [mem_univ, union_singleton, mem_insert_iff, mem_range, true_iff]
    by_cases hx_zero : x = 0
    · left
      assumption
    · right
      exact FiniteDimensional.isUnit F hx_zero
  -- Therefore F is finite
  rw [← Set.finite_univ_iff, h_eq]
  apply Set.Finite.union
  · exact Set.finite_range Units.val
  · exact Set.finite_singleton 0

/-- In an infinite cyclic group G, every non-identity element has infinite order.
    This is because if G is infinite and cyclic, then G ≅ ℤ, and in ℤ every non-zero element
    generates an infinite subgroup. -/
lemma orderOf_eq_zero_of_cyclic_of_infinite (G : Type*) [Group G] [IsCyclic G] [Infinite G] :
    ∀ g : G, g ≠ 1 → orderOf g = 0 := by
  -- First acquire a generator of G
  rcases @IsCyclic.exists_generator G _ _ with ⟨g, hg⟩
  intro u hu
  -- Show that the generator g has infinite order
  have : orderOf g = 0 := by
    apply Infinite.orderOf_eq_zero_of_forall_mem_zpowers hg
  -- Any element u can be written as a power of the generator g
  have gu : ∃ k : ℤ, g ^ k = u := by
    have gu' : u ∈ Subgroup.zpowers g := hg u
    simp only [Subgroup.zpowers, Subgroup.mem_mk, mem_range] at gu'
    exact gu'
  rcases gu with ⟨k, hk⟩
  -- Replace u by g^k and show that g^k also has infinite order
  rw [← hk]
  refine orderOf_eq_zero_iff'.mpr ?_
  intro n hn
  rw [orderOf_eq_zero_iff'] at this
  contrapose! this
  -- Case analysis on the sign of k
  by_cases zk : k = 0
  · -- If k = 0, then u = 1, contradicting u ≠ 1
    simp only [zk, zpow_zero] at hk
    exfalso
    exact hu (Eq.symm hk)
  by_cases gk : k > 0
  · -- If k > 0, use the fact that (g^k)^n = g^(kn) = 1 implies g^(kn) = 1
    use (Int.toNat k) * n
    simp only [Int.lt_toNat, CharP.cast_eq_zero, gk, mul_pos_iff_of_pos_left, hn, true_and]
    rw [pow_mul, ← this]
    congr 1
    rw [← zpow_natCast]
    congr 1
    omega
  -- If k < 0, use similar reasoning with absolute value
  have lk : k < 0 := by omega
  use Int.natAbs k * n
  simp only [hn, mul_pos_iff_of_pos_right, Int.natAbs_pos, ne_eq]
  constructor
  · exact zk
  rw [pow_mul]
  -- Use the fact that g^(-|k|) = (g^|k|)^(-1)
  have this' : (g ^ (-k)) ^ n = 1 := by
    rw [← inv_one, ← this]
    group
  rw [← this']
  congr 1
  rw [← zpow_natCast]
  congr 1
  omega

/-- If E is a field extension of F and the unit group Eˣ is generated by a single element g,
    then E = F[g]. This shows that E is a simple extension of F generated by g. -/
lemma simple_extension_of_cyclic_generator
    (F : Type*) {E : Type*} [Field F] [Field E] [Algebra F E]
    (g : Eˣ) (hg : ∀ (x : Eˣ), x ∈ Subgroup.zpowers g) :
    ⊤ = IntermediateField.adjoin F {g.val} := by
  ext x
  constructor
  · intro _
    -- Every element x ∈ E is either 0 or a unit
    by_cases hx_zero : x = 0
    · -- If x = 0, then x ∈ F[g]
      rw [hx_zero]
      exact IntermediateField.zero_mem (IntermediateField.adjoin F {g.val})
    · -- If x ≠ 0, then x ∈ Eˣ
      have x_unit : IsUnit x := FiniteDimensional.isUnit E hx_zero
      obtain ⟨u, hu⟩ := x_unit
      -- Since g generates all of Eˣ, we have u = g^k for some integer k
      obtain ⟨k, hk⟩ := hg u
      rw [← hu, ← hk]
      -- Therefore x = g^k ∈ F[g]
      simp only [Units.val_zpow_eq_zpow_val]
      apply IntermediateField.pow_mem
      apply IntermediateField.subset_adjoin
      simp only [mem_singleton_iff]
  · -- The reverse inclusion is trivial: F[g] ⊆ E = ⊤
    intro hx
    simp only [IntermediateField.mem_top]

/-- If F is a field of characteristic 2 with a cyclic unit group, then F is finite.
    This is proved by showing that the generator of the unit group is algebraic, so that
    the extension F/𝔽₂ ≃ 𝔽₂[g] is finite dimensional. -/
lemma Field.finite_of_char_two_of_cyclic_units (F : Type*) [Field F] [CharP F 2] [IsCyclic Fˣ] :
    Finite F := by
  -- Since char F = 2, we have a natural algebra structure F over 𝔽₂
  haveI : Algebra (ZMod 2) F := ZMod.algebra _ _

  -- Since Fˣ is cyclic, let g be a generator of Fˣ
  obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := Fˣ)

  -- Show that g is algebraic over 𝔽₂. We shall find a polynomial relation it satisfies.
  have g_integral : IsIntegral (ZMod 2) (g.val : F) := by
    rw [← isAlgebraic_iff_isIntegral]

    by_cases gp1_ne : 1 + g.val = 0
    · -- Case 1: 1 + g = 0, so g = -1 = 1 (in characteristic 2)
      apply_fun (fun x => x - 1) at gp1_ne
      ring_nf at gp1_ne
      use Polynomial.X - 1
      rw [CharTwo.neg_eq] at gp1_ne
      rw [gp1_ne]
      simp only [ne_eq, map_sub, Polynomial.aeval_X, map_one, sub_self, and_true]
      exact Polynomial.X_sub_C_ne_zero 1
    · -- Case 2: 1 + g ≠ 0, so 1 + g is a unit, hence a power of g
      obtain ⟨g₁, hg₁⟩ := FiniteDimensional.isUnit F gp1_ne
      obtain ⟨n, hn⟩ := hg g₁
      simp only at hn
      rw [← hn] at hg₁
      -- n cannot be zero (otherwise 1 + g = 1, so g = 0, contradiction)
      have n_ne_zero : n ≠ 0 := by
        intro h
        rw [h] at hg₁
        simp at hg₁

      by_cases n_neg : n < 0
      · -- Case 2.1: n < 0
        let n' := (-n).toNat
        apply_fun (fun x => x * g.val ^ (-n)) at hg₁
        rw [add_mul] at hg₁
        norm_cast at hg₁
        conv at hg₁ => rhs; rhs; congr; lhs; rw [show g = g ^ (1:ℤ) by simp]
        repeat rw [←zpow_add] at hg₁
        conv at hg₁ => lhs; simp only [add_neg_cancel, zpow_zero, Units.val_one]
        rw [show -n = n' by
          unfold n'
          simp only [Int.ofNat_toNat, left_eq_sup, Int.neg_nonneg]
          linarith] at hg₁
        norm_cast at hg₁
        simp only [Units.val_pow_eq_pow_val, one_mul] at hg₁
        -- g satisfies the polynomial X^(1+n') + X^n' - 1 = 0
        use (Polynomial.X ^ (1 + n') + Polynomial.X ^ n' - 1)
        constructor
        · intro tmp
          apply_fun fun f => f.aeval (0 : F) at tmp
          simp only [map_sub, map_add, map_pow, Polynomial.aeval_X, ne_eq, Nat.add_eq_zero,
            one_ne_zero, false_and, not_false_eq_true, zero_pow, zero_add, map_one, map_zero] at tmp
          haveI : n' ≠ 0 := by
            unfold n'
            simp only [ne_eq, Int.toNat_eq_zero, Left.neg_nonpos_iff, not_le]
            linarith
          rw [zero_pow this] at tmp
          simp only [zero_sub, neg_eq_zero, one_ne_zero] at tmp
        · simp only [map_sub, map_add, map_pow, Polynomial.aeval_X, map_one, hg₁]
          ring
      · -- Case 2.2: n ≥ 0
        push_neg at n_neg
        let n' := n.toNat
        rw [show n = n' by
          unfold n'
          simp only [Int.ofNat_toNat, left_eq_sup]
          linarith] at hg₁
        simp only [zpow_natCast, Units.val_pow_eq_pow_val] at hg₁
        -- g satisfies the polynomial X^n' - X - 1 = 0
        use (Polynomial.X ^ n' - Polynomial.X - 1)
        simp only [ne_eq, map_sub, map_pow, Polynomial.aeval_X, hg₁,
          add_sub_cancel_right, map_one, sub_self, and_true]
        intro tmp

        apply_fun fun f => f.aeval (0 : F) at tmp
        simp only [map_sub, map_pow, Polynomial.aeval_X, sub_zero, map_one, map_zero] at tmp
        haveI : n' ≠ 0 := by
          unfold n'
          by_contra! h
          apply n_ne_zero
          rw [← Int.toNat_of_nonneg n_neg, h]
          simp only [CharP.cast_eq_zero]
        rw [zero_pow this] at tmp
        simp only [zero_sub, neg_eq_zero, one_ne_zero] at tmp

  -- Since g is integral over 𝔽₂, the extension 𝔽₂[g] is finite dimensional
  haveI : FiniteDimensional (ZMod 2) (IntermediateField.adjoin (ZMod 2) {g.val}) :=
    IntermediateField.adjoin.finiteDimensional g_integral

  -- But F = 𝔽₂[g]
  have field_eq : (⊤ : IntermediateField (ZMod 2) F) =
      IntermediateField.adjoin (ZMod 2) {g.val} :=
    simple_extension_of_cyclic_generator (ZMod 2) g hg

  -- Thus F is finite dimensional over 𝔽₂
  haveI : FiniteDimensional (ZMod 2) F := by
    have iso : (⊤ : IntermediateField (ZMod 2) F) ≃ₐ[ZMod 2] F :=
      IntermediateField.topEquiv
    symm at iso
    rw [field_eq] at iso
    exact FiniteDimensional.of_injective iso.toLinearMap iso.injective

  -- Since 𝔽₂ is finite and F is finite dimensional over 𝔽₂, F is finite
  exact Module.finite_of_finite (ZMod 2)

/-- Every field with a cyclic unit group is finite.
    The proof is by contradiction: if F is infinite with cyclic Fˣ, then all non-identity
    elements of Fˣ have infinite order, but -1 has order 2 unless char F = 2. So char F = 2,
    and then F is finite by the previous lemma. -/
theorem Field.finite_of_cyclic_units (F : Type*) [Field F] [IsCyclic Fˣ] :
    Finite F := by
  -- Proof by contradiction - assume F is infinite
  by_contra h_infinite

  -- If F is infinite, then so is Fˣ (since F = Fˣ ∪ {0})
  haveI : Infinite F := not_finite_iff_infinite.mp h_infinite

  haveI : Infinite Fˣ := by
    contrapose! h_infinite
    simp only [not_infinite_iff_finite] at h_infinite
    exact finite_of_finite_units F

  -- In an infinite cyclic group, all non-identity elements have infinite order
  have h_infinite_order := orderOf_eq_zero_of_cyclic_of_infinite Fˣ

  -- But -1 has order 2 unless char F = 2, so char F = 2
  haveI : CharP F 2 := by
    -- Show that -1 must have finite order unless char F = 2
    specialize h_infinite_order (-1 : Fˣ)
    contrapose! h_infinite_order
    constructor
    · -- Show -1 ≠ 1 (unless char F = 2)
      haveI : ringChar F ≠ 2 := by
        contrapose! h_infinite_order
        haveI := ringChar.charP F
        rw [h_infinite_order] at this
        exact this
      contrapose! this
      rw [← neg_one_eq_one_iff]
      apply_fun (fun x => x.val) at this
      exact this
    · -- Compute the orderOf (-1)
      rw [← orderOf_units]
      push_cast
      rw [orderOf_neg_one]
      haveI : ringChar F ≠ 2 := by
        intro h_char
        haveI := ringChar.charP F
        rw [h_char] at this
        contradiction
      simp [this]

  -- Now char F = 2 and Fˣ cyclic, so F is finite by our lemma
  have h_finite : Finite F := finite_of_char_two_of_cyclic_units F

  -- This contradicts our assumption that F is infinite
  exact h_infinite h_finite
